<?php
$user_id = (int) $this->session->userdata('user_id');
$purchase_history = $this->crud_model->purchase_history($user_id);
$purchase_rows = $purchase_history->result_array();

if (!function_exists('youngo_account_e')) {
    function youngo_account_e($value) {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    }
}
?>

<section class="youngo-account-hero">
    <div class="youngo-container">
        <nav class="youngo-breadcrumb" aria-label="<?php echo get_phrase('Breadcrumb'); ?>">
            <a href="<?php echo site_url('home'); ?>"><?php echo get_phrase('Home'); ?></a>
            <span>/</span>
            <span><?php echo get_phrase('Purchase history'); ?></span>
        </nav>

        <p class="youngo-eyebrow"><?php echo get_phrase('Billing'); ?></p>
        <h1><?php echo get_phrase('Purchase history'); ?></h1>
        <p><?php echo get_phrase('Review course purchases and open invoices generated by the existing Academy LMS payment records.'); ?></p>
    </div>
</section>

<section class="youngo-account-page">
    <div class="youngo-container">
        <div class="youngo-account-layout">
            <?php include 'profile_menus.php'; ?>

            <div class="youngo-account-panel">
                <div class="youngo-account-panel__header">
                    <div>
                        <p class="youngo-eyebrow"><?php echo get_phrase('Orders'); ?></p>
                        <h2><?php echo get_phrase('Purchased courses'); ?></h2>
                    </div>
                    <a class="youngo-button youngo-button--secondary youngo-button--small" href="<?php echo site_url('home/courses'); ?>"><?php echo get_phrase('Browse courses'); ?></a>
                </div>

                <?php if (count($purchase_rows) > 0): ?>
                    <div class="youngo-purchase-list">
                        <?php foreach ($purchase_rows as $each_purchase): ?>
                            <?php
                            $course_details = $this->crud_model->get_course_by_id($each_purchase['course_id'])->row_array();
                            if (empty($course_details)) {
                                continue;
                            }
                            $course_url = site_url('home/course/' . rawurlencode(slugify($course_details['title'])) . '/' . $course_details['id']);
                            ?>
                            <article class="youngo-purchase-card">
                                <a class="youngo-purchase-card__media" href="<?php echo $course_url; ?>">
                                    <img loading="lazy" src="<?php echo $this->crud_model->get_course_thumbnail_url($course_details['id']); ?>" alt="<?php echo youngo_account_e($course_details['title']); ?>">
                                </a>

                                <div class="youngo-purchase-card__body">
                                    <div>
                                        <p class="youngo-eyebrow"><?php echo ucfirst($each_purchase['payment_type']); ?></p>
                                        <h3><a href="<?php echo $course_url; ?>"><?php echo youngo_account_e($course_details['title']); ?></a></h3>
                                    </div>

                                    <div class="youngo-purchase-card__meta">
                                        <span><i class="fa-regular fa-calendar"></i> <?php echo date('d M Y', $each_purchase['date_added']); ?></span>
                                        <strong><?php echo currency($each_purchase['amount']); ?></strong>
                                    </div>

                                    <div class="youngo-purchase-card__actions">
                                        <a class="youngo-button youngo-button--small youngo-button--secondary" href="<?php echo $course_url; ?>"><?php echo get_phrase('Course details'); ?></a>
                                        <a class="youngo-button youngo-button--small" href="<?php echo site_url('home/invoice/' . $each_purchase['id']); ?>"><?php echo get_phrase('Invoice'); ?></a>
                                    </div>
                                </div>
                            </article>
                        <?php endforeach; ?>
                    </div>
                <?php else: ?>
                    <div class="youngo-commerce-empty">
                        <div class="youngo-commerce-empty__icon"><i class="fa-solid fa-receipt"></i></div>
                        <p class="youngo-eyebrow"><?php echo get_phrase('No purchases yet'); ?></p>
                        <h2><?php echo get_phrase('Purchase history is empty'); ?></h2>
                        <p><?php echo get_phrase('When a course purchase is completed through the existing LMS checkout, it will appear here with invoice access.'); ?></p>
                        <a class="youngo-button" href="<?php echo site_url('home/courses'); ?>"><?php echo get_phrase('Browse courses'); ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
